import { useEffect, useState } from 'react'
import { Sparkles, Loader2, AlertCircle } from 'lucide-react'
import { getAreaSummary } from '@/api/issueApi'
import { useLocationContext } from '@/context/LocationContext'

export default function AiSummaryBanner() {
  const { location } = useLocationContext()
  const [summary, setSummary] = useState(null)
  const [area, setArea] = useState(null)
  const [cached, setCached] = useState(false)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)

  useEffect(() => {
    setLoading(true)
    setError(false)
    setSummary(null)

    getAreaSummary(location)
      .then(({ data }) => {
        // Don't show the fallback message as a summary — hide the banner instead
        if (data.summary === 'Summary temporarily unavailable.' || data.summary === 'No issues reported yet.') {
          setSummary(null)
        } else {
          setSummary(data.summary)
          setArea(data.area)
          setCached(data.cached)
        }
      })
      .catch(() => setError(true))
      .finally(() => setLoading(false))
  }, [location])

  if (loading) {
    return (
      <div className="mb-6 rounded-xl border border-primary/20 bg-primary/5 px-5 py-4">
        <div className="flex items-center gap-2 text-sm text-primary font-medium mb-2">
          <Sparkles className="h-4 w-4" />
          AI Summary
        </div>
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Loader2 className="h-3.5 w-3.5 animate-spin" />
          Generating summary…
        </div>
      </div>
    )
  }

  if (error || !summary) return null

  const areaLabel = location ? location.name.split(',')[0].trim() : 'All locations'

  return (
    <div className="mb-6 rounded-xl border border-primary/20 bg-primary/5 px-5 py-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary" />
          <span className="text-sm font-semibold text-primary">AI Summary</span>
          <span className="rounded-full bg-primary/15 px-2.5 py-0.5 text-xs font-medium text-primary">
            {areaLabel}
          </span>
        </div>
        {cached && (
          <span className="text-xs text-muted-foreground">cached</span>
        )}
      </div>

      {/* Summary paragraph */}
      <p className="text-sm leading-relaxed text-foreground">{summary}</p>

      {/* Footer */}
      <p className="mt-3 text-xs text-muted-foreground">
        Based on issues reported in the past 3 days · Generated by Gemini
      </p>
    </div>
  )
}
